# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: GoLang Test
    # You may pin to the exact commit or the version.
    # uses: n8maninger/action-golang-test@a8263fc1a85b63937b1b365946518675ceab5740
      uses: n8maninger/action-golang-test@v1
      with:
        # the package to run the tests for
        package: optional
        # additional go test command line arguments, individual arguments should be separated by ';'
        args: optional 
        # outputs a warning for long running tests, -1 to disable
        show-long-running-tests: optional
        # includes package output in the parsed output
        show-package-output: optional
        # shows tests that were run and passed
        show-passed-tests: optional
        # shows the unparsed std-out from go test instead of the parsed output
        show-stdout: optional
        # skips installing and setting up Go, useful for defining additional parameters for actions/setup-go
        skip-go-install: optional
      

